- name: TASKS FOR ALL HOSTS
  hosts: all
  become: yes
  vars:
    db_user: "{{ hostvars[inventory_hostname]['DB_USER'] }}"
    db_host: "{{ hostvars[inventory_hostname]['DB_HOST'] }}"
    db_repl_user: "{{ hostvars[inventory_hostname]['DB_REPL_USER'] }}"
    db_repl_host: "{{ hostvars[inventory_hostname]['DB_REPL_HOST'] }}"
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 86400

    - name: Add PostgreSQL APT repository key
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present

    - name: Add PostgreSQL APT repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main"
        state: present
        filename: "pgdg"

    - name: Install required packages
      apt:
        name:
          - postgresql-14
          - postgresql-contrib
          - postgresql-common
          - python3
          - python3.10
          - python3-dev
          - python3-pip
          - jq
        state: present

    - name: Check PostgreSQL version
      command: psql --version
      register: psql_version
      ignore_errors: true

    - name: Check if PostgreSQL is installed
      fail:
        msg: "PostgreSQL is not installed on this host."
      when: psql_version.failed

    - name: Check if PostgreSQL cluster exists
      block:
        - name: Check if PostgreSQL cluster exists
          shell: |
            if pg_lsclusters | grep -q '14 main'; then
              echo 'Cluster exists'
            else
              pg_createcluster 14 main
            fi
          register: create_cluster
      rescue:
        - name: Handle cluster creation failure
          debug:
            msg: "Cluster creation failed."

    - name: Check if PostgreSQL is running
      command: pg_ctlcluster 14 main status
      register: postgres_status
      ignore_errors: true

    - name: Start PostgreSQL cluster if not running
      command: pg_ctlcluster 14 main start
      when: postgres_status.stdout.find('is not running') != -1

- name: CONFIGURATING MASTERDB
  hosts: ansible1
  become: yes
  vars:
    db_user: "{{ hostvars[inventory_hostname]['DB_USER'] }}"
    db_host: "{{ hostvars[inventory_hostname]['DB_HOST'] }}"
    db_repl_user: "{{ hostvars[inventory_hostname]['DB_REPL_USER'] }}"
    db_repl_host: "{{ hostvars[inventory_hostname]['DB_REPL_HOST'] }}"
    db_database: "{{ hostvars[inventory_hostname]['DB_DATABASE'] }}"
  tasks:
    - name: Install psycopg2
      pip:
        name: psycopg2-binary

    - name: Setup pg_hba.conf
      blockinfile:
        create: true
        path: /etc/postgresql/14/main/pg_hba.conf
        block: |
          local all {{ db_user }} peer
          host all all "{{ db_host }}"/32 trust
          host replication {{ db_repl_user }} {{ db_repl_host }}/24 trust

    - name: Setup postgresql.conf
      blockinfile:
        create: true
        path: /etc/postgresql/14/main/postgresql.conf
        block: | 
          listen_addresses = '*'
          port = 5432
          log_destination = 'stderr'
          logging_collector = on
          log_directory = '/var/log/postgresql/'
          log_filename = 'postgresql.log'
          log_file_mode = 0644
          archive_mode = on
          archive_command = 'cp %p /oracle/pg_data/archive/%f'
          max_wal_senders = 10
          wal_level = replica
          wal_log_hints = on
          log_replication_commands = on

    - name: Allow PostgreSQL through firewall
      ufw:
        rule: allow
        port: '5432'
        proto: 'tcp'
        state: enabled

    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted

    - name: Create master database
      community.general.postgresql_db:
        name: "{{ db_database }}"
        encoding: UTF-8
        template: template0
      become: yes
      become_user: postgres

    - name: Create Emails table
      command: psql -d {{ db_database }} -c "CREATE TABLE emails (id serial PRIMARY KEY, email text);"
      become_user: postgres
      ignore_errors: true

    - name: Create Phone Numbers table
      command: psql -d {{ db_database }} -c "CREATE TABLE phone_numbers (id serial PRIMARY KEY, phone_number text);"
      become_user: postgres
      ignore_errors: true

    - name: Change postgres password
      command: psql -c "ALTER USER {{ db_user }} WITH PASSWORD '{{ hostvars[inventory_hostname]['DB_PASSWORD'] }}';"
      become_user: postgres

    - name: Create replication user
      command: psql -c "CREATE USER {{ db_repl_user }} REPLICATION LOGIN SUPERUSER PASSWORD '{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}';"
      become_user: postgres
      ignore_errors: true

- name: CONFIGURATING SLAVEDB
  hosts: ansible2
  become: yes
  vars:
    db_host: "{{ hostvars[inventory_hostname]['DB_HOST'] }}"
    db_repl_user: "{{ hostvars[inventory_hostname]['DB_REPL_USER'] }}"
    db_repl_password: "{{ hostvars[inventory_hostname]['DB_REPL_PASSWORD'] }}"
  tasks:
    - name: Find out if PostgreSQL is initialized
      command: pg_ctlcluster 14 main status
      register: postgres_status
      ignore_errors: true
      become_user: root

    - name: Initialize PostgreSQL
      command: pg_createcluster 14 main
      when: postgres_status.stdout.find('specified cluster \'14 main\' does not exist') != -1
      become_user: root

    - name: Get postgresql.conf path
      shell: "pg_lsclusters --json | jq -r '.[].configdir'"
      register: pg_conf_path

    - name: Setup postgresql.conf
      blockinfile:
        create: true
        path: "{{ pg_conf_path.stdout }}/postgresql.conf"
        block: |
          listen_addresses = 'localhost, {{ hostvars[inventory_hostname]['DB_REPL_HOST'] }}'
          port = {{ hostvars[inventory_hostname]['DB_REPL_PORT'] }}

    - name: Stop PostgreSQL
      service:
        name: postgresql
        state: stopped

    - name: Clean PostgreSQL main directory
      file:
        path: /var/lib/postgresql/14/main
        state: absent
      become: true

    - name: Execute pg_basebackup
      command: pg_basebackup -R -h {{ db_host }} -U {{ db_repl_user }} -D /var/lib/postgresql/14/main -P
      become_user: postgres
      environment:
        PGPASSWORD: "{{ db_repl_password }}"
      register: basebackup_result
      failed_when: basebackup_result.rc != 0

    - name: Set permissions for the replication directory
      file:
        path: /var/lib/postgresql/14/main/
        owner: postgres
        group: postgres
        recurse: yes
      become: true

    - name: Start PostgreSQL
      service:
        name: postgresql
        state: started

- name: CONFIGURATING BOT
  hosts: ansible1
  become: yes
  vars:
    bot_path: "/etc/bot_pozhidaevsd"
  tasks:
    - name: Install Python packages
      pip:
        name:
          - python-telegram-bot==13.7
          - psycopg2-binary
          - python-dotenv
          - paramiko
          - requests
          - urllib3==1.26.15
          - requests-toolbelt==0.10.1
          - docker
        state: latest

    - name: Create working directory
      file:
        path: "{{ bot_path }}"
        owner: ansible1
        group: ansible1
        state: directory
        mode: '0777'

    - name: Get a git repository
      git:
        repo: https://github.com/toska-varis/devops_bot.git
        dest: "{{ bot_path }}"
        version: main

    - name: Run Bot
      command: python3 {{ bot_path }}/bot.py
      environment:
        TOKEN: "{{ hostvars[inventory_hostname]['TOKEN'] }}"
        DB_HOST: "{{ hostvars[inventory_hostname]['DB_HOST'] }}"
        DB_PORT: "{{ hostvars[inventory_hostname]['DB_PORT'] }}"
        DB_USER: "{{ hostvars[inventory_hostname]['DB_USER'] }}"
        DB_PASSWORD: "{{ hostvars[inventory_hostname]['DB_PASSWORD'] }}"
        DB_DATABASE: "{{ hostvars[inventory_hostname]['DB_DATABASE'] }}"
        RM_HOST: "{{ hostvars[inventory_hostname]['RM_HOST'] }}"
        RM_PORT: "{{ hostvars[inventory_hostname]['RM_PORT'] }}"
        RM_USER: "{{ hostvars[inventory_hostname]['RM_USER'] }}"
        RM_PASSWORD: "{{ hostvars[inventory_hostname]['RM_PASSWORD'] }}"
      become_user: ansible1

        
